//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Casm.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Casm.Antlr {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ICasmListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class CasmBaseListener : ICasmListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CasmParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProg([NotNull] CasmParser.ProgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CasmParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProg([NotNull] CasmParser.ProgContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CasmParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] CasmParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CasmParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] CasmParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CasmParser.label"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLabel([NotNull] CasmParser.LabelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CasmParser.label"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLabel([NotNull] CasmParser.LabelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CasmParser.instruction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstruction([NotNull] CasmParser.InstructionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CasmParser.instruction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstruction([NotNull] CasmParser.InstructionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CasmParser.directive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDirective([NotNull] CasmParser.DirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CasmParser.directive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDirective([NotNull] CasmParser.DirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CasmParser.expressionList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpressionList([NotNull] CasmParser.ExpressionListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CasmParser.expressionList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpressionList([NotNull] CasmParser.ExpressionListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CasmParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] CasmParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CasmParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] CasmParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CasmParser.register"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRegister([NotNull] CasmParser.RegisterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CasmParser.register"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRegister([NotNull] CasmParser.RegisterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CasmParser.registerReference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRegisterReference([NotNull] CasmParser.RegisterReferenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CasmParser.registerReference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRegisterReference([NotNull] CasmParser.RegisterReferenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CasmParser.comment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComment([NotNull] CasmParser.CommentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CasmParser.comment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComment([NotNull] CasmParser.CommentContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace Casm.Antlr
